services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/projects_app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: